lib/blog_app_web/router.ex
defmodule BlogAppWeb.Router do
  use BlogAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BlogAppWeb do
    pipe_through :browser
    resources "/post", PostController do
      resources "/comment", CommentController
    end
    get "/", PostController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", BlogAppWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: BlogAppWeb.Telemetry
    end
  end
end

lib/blog_app/blog/post.ex
defmodule BlogApp.Blog.Post do
  use Ecto.Schema
  import Ecto.Changeset

  schema "posts" do
    field :body, :string
    field :title, :string
    has_many :comments, BlogApp.Blog.Comment

    timestamps()
  end

  @doc false
  def changeset(post, attrs) do
    post
    |> cast(attrs, [:title, :body])
    |> validate_required([:title, :body])
  end
end

lib/blog_app_web/controllers/post_controller.ex
defmodule BlogAppWeb.PostController do
    use BlogAppWeb, :controller
    alias BlogApp.Blog
    alias BlogApp.Blog.{Post, Comment}

    def new(conn, _params) do
        changeset=Blog.change_post(%Post{})
        render(conn, :new, changeset: changeset)
    end

    def create(conn, %{"post"=>post_params}) do
       case Blog.create_post(post_params) do
           {:ok, post} ->
                redirect(conn, to: Routes.post_path(conn, :show, post))
            {:error, %Ecto.Changeset{}=changeset} ->
                render(conn, :new, changeset: changeset)
       end 
    end

    def show(conn, %{"id"=>id}) do
        post=Blog.get_post!(id)
        comment_changeset=Blog.change_comment(%Comment{})
        
        render(conn, :show, post: post, comment_changeset: comment_changeset)
    end

    def edit(conn, %{"id"=> id}) do
        post=Blog.get_post!(id)
        changeset=Blog.change_post(post)
        render(conn, :edit, post: post, changeset: changeset)
    end

    def update(conn, %{"id"=>id, "post"=>post_params}) do
        post=Blog.get_post!(id)
        case Blog.update_post(post, post_params) do
            {:ok, post} ->
                redirect(conn, to: Routes.post_path(conn, :show, post))
            {:error, %Ecto.Changeset{}=changeset} ->
                render(conn, :edit, post: post, changeset: changeset)    
        end
    end

    def index(conn, _params) do
        posts=Blog.list_posts
        render(conn, :index, posts: posts)
      end
end

lib/blog_app_web/views/post_view.ex
defmodule BlogAppWeb.PostView do
    use BlogAppWeb, :view
end

lib/blog_app_web/templates/post/edit.html.eex
<%=render "form.html", Map.put(assigns, :action, Routes.post_path(@conn, :update, @post))%>

lib/blog_app_web/templates/post/form.html.eex
<%=form_for @changeset, @action, fn f->%>
    Title: <%=text_input f, :title%>
    Body: <%=text_input f, :body%>
    <%=submit "Submit"%>
<%end%>

lib/blog_app_web/templates/post/index.html.eex
<div style="background-color: black; color: white; margin-bottom: 20px"><%=link "New Post", to: Routes.post_path(@conn, :new)%></div>
<%=for post <- @posts do%>
<p><%=link post.title, to: Routes.post_path(@conn, :show, post)%></p>
<p><%=post.body%></p>
<%noComments=if length(post.comments)>1, do: "comments", else: "comment"%>
<%=link "#{length(post.comments)} #{noComments}", to: Routes.post_comment_path(@conn, :index, post)%>
<p>---------------------------</p>
<%end%>

lib/blog_app_web/templates/post/new.html.eex
<%=render "form.html", Map.put(assigns, :action, Routes.post_path(@conn, :create))%>

lib/blog_app_web/templates/post/show.html.eex
<p>Title: <%=@post.title%></p>
<p>Body: <%=@post.body%></p>
<h3>Comments (<%=length(@post.comments)%>)</h3>
<%=for comment <- @post.comments do%>
    <p>Author: <%=comment.author%></p>
    <p>Content: <%=comment.body%></p>
<%end%>
 <h3>Add Comment</h3>
 <%=form_for @comment_changeset, Routes.post_comment_path(@conn, :create, @post), fn f ->%>
    Name: <%=text_input f, :author%>
    Body: <%=textarea f, :body%>
    <%=submit "Comment"%>
<%end%>

<p><%=link("Edit", to: Routes.post_path(@conn, :edit, @post))%></p>

<%=link("Back", to: Routes.post_path(@conn, :index))%>